### ISSUE TITLE
Automatically detect current path

### ISSUE THREAD

**Issue by JLee21** [vyder/atom-cpp-generator#1]
Hi!

Instead of typing the path to the newly generated C++ files,
is it possible to detect which file you currently have highlighted/selected within Atom and then use that as the base path for the new files?

Thanks,

**Comment by vyder** [comment]
It looks like you can get the currently selected file via `atom.workspace.getActiveTextEditor()?.getPath()` accoding to this [SO post](https://stackoverflow.com/a/44082956/834459).

I moved away from C++ for my current project, so I probably won't get around to building this myself for another 6 months or so.

Feel free to take a shot at implementing it, I'll be happy to merge a PR.

**Comment by vyder** [comment]
Well, one thing led to another, and I ended up implementing it myself this morning.

I've released it as [v1.0.1](https://github.com/vyder/atom-cpp-generator/releases/tag/v1.0.1)
