### ISSUE TITLE
Allow Use Selected Filepath to also include folders

### ISSUE THREAD

**Issue by codedcosmos** [vyder/atom-cpp-generator#3]
The "Use Selected Filepath" option only works when there is already a file in the directory you want to create the files in.

Please allow this package to also work when selecting a folder. Creating that folders first two files.

Thanks

**Comment by vyder** [comment]
Thanks for closing this...did you figure it out after 2 years? 😄

**Comment by codedcosmos** [comment]
I stopped using atom, and mostly forgot what the bug was about.

**Comment by vyder** [comment]
Works for me - I've stopped using Atom too 😂

**Comment by codedcosmos** [comment]
What do you use these days? Personally I have switched to intellij

**Comment by vyder** [comment]
I still default to SublimeText (now on 3, previously 2). I was using ST2 even while I used Atom previously...I find that nothing else is nearly as fast on my machine (I'm still on a 2011 Macbook Air). And I'm very used to being able to make snippets and plugins for it quickly as and when the need arises - I haven't bothered learning a new editor that well yet.

That being said, most of the frameworks I use are web technologies like Ruby/Rails/Node so I don't really find the need for intellisense or something fancy.

Are you doing Java/Android work?

**Comment by codedcosmos** [comment]
I'm in uni and most of my programming is just for hobbies. At the time I didn't have access to a good cpp ide but now I'm in uni so I have a clion licence for free. 

Iv wanted to learn vim but it seems like it's not worth it.

**Comment by vyder** [comment]
Ah I see - yes, all of JetBrains products are definitely the best IDEs out there.

I'm not a fan of vim personally - I use nano for most of command-line editing needs - but it's definitely nowhere near as powerful.

**Comment by codedcosmos** [comment]
I will also typically use nano if I'm editing something in the terminal. Though I never do work in the terminal. Only if im quickly editing some config file or of that nature. Honestly 90% of the time when using the terminal it's simply to upgrade my packages.
